Repository Amsterdam/cms_search, pull requests merged in 2020-04, with the labels that each got.

#72 Update to a stable version of TypeScript
  package-lock.json
  package.json
Labels: dependencies

#71 Implement SearchResult for Map results
  src/generated/graphql.schema.json
  src/generated/graphql.ts
  src/graphql/graphql.schema.ts
  src/map/graphql.ts
Labels: bug

#73 Fix issues causing building of URLs to map to break
  assets/map-layers.config.json
  src/map/data.ts
Labels: bug

#99 Fix issues with FuseJS results
  src/map/graphql.ts
  src/map/typeahead.ts
  src/utils/from-fuse-result.test.ts
  src/utils/from-fuse-result.ts
Labels: bug

#103 Add Dependabot config
  .dependabot/config.yml
Labels: enhancement

#113 Get results per type of CMS content for autosuggest
  src/es/cms/typeahead.ts
  src/graphql/search/cms/config.ts
  src/map/typeahead.ts
  src/typeahead/index.ts
Labels: bug

#116 Add themes to map collections
  assets/map-collections.config.json
  src/generated/graphql.schema.json
  src/generated/graphql.ts
  src/generated/map-collection.ts
  src/graphql/graphql.schema.ts
  src/map/data.ts
Labels: enhancement
